### ISSUE TITLE
Graph Bars Don't Render in 5.4.0

### ISSUE THREAD

**Issue by ardichoke** [NatelEnergy/grafana-discrete-panel#78] opened 2018-12-03 15:25 UTC
After upgrading to Grafana 5.4.0, the horizontal bars no longer render properly. When hovering over them, I can see that they're there (the tooltip pops up displaying what the data is), however, there are no colored bars or text rendered.

Screenshot for (very boring) example. 
![2018-12-03 10_23_52-grafana - smartthings](https://user-images.githubusercontent.com/112836/49382962-ae7a6280-f6e5-11e8-91b9-a8a5fb58df6e.png)

**Comment by bmorris591** [comment] 2018-12-03 15:39
I have this same issue. I have found that going to the edit dialogue for the panel and clicking in and out of one of the colour selectors causes the bar to be rendered correctly - but only until a reload.

**Comment by ryantxu** [comment] 2018-12-03 18:03
I just added a fix to master... looks like the initialization is not called anymore :(

I'll wait for a response and then try to post a new build if we are supposed to hack around it :(

**Comment by ryantxu** [comment] 2018-12-03 18:14
I'll keep this open till we get a sense if we shoud add the hack or wait for it to get fixed in grafana

**Comment by krikk** [comment] 2018-12-11 10:48
seems like it was fixed in grafana 5.4.1... working normal for me.

**Comment by FUSAKLA** [comment] 2018-12-11 10:49
Yes, I can confirm it works nicely.

**Comment by bmorris591** [comment] 2018-12-11 11:19
Yup, seem to be fixed 5.4.1

**Comment by PaulFreund** [comment] 2018-12-11 13:35
Can confirm fixed with Grafana 5.4.1 and Grafana Discrete Panel 0.0.8-pre

**Closed** 2018-12-13 16:11 UTC
Labels: bug
